### PR TITLE
feat: update ComputePlan statuses

### PR DESCRIPTION
**Pull request by guilhem-barthes**
Fixes FL-1422

### CODE REVIEW

**Comment by guilhem-barthes** [comment]
/e2e --refs=orchestrator=feat/update-computeplan-status,susbtra-backend=feat/update-computeplan-status,substra=feat/update-computeplan-status

**Comment by Owlfred** [comment]
Invalid repository in --refs: "susbtra-backend". Supported repositories: orchestrator, substra-backend, substra-frontend, substra-tools, substrafl, substra, substra-tests, substra-documentation, substra-ci

**Comment by guilhem-barthes** [comment]
/e2e --refs=orchestrator=feat/update-computeplan-status,substra-backend=feat/update-computeplan-status,substra=feat/update-computeplan-status

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
/e2e --refs=orchestrator=feat/update-computeplan-status,substra-backend=feat/update-computeplan-status,substra=feat/update-computeplan-status

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
/e2e --refs=orchestrator=feat/update-computeplan-status,substra-backend=feat/update-computeplan-status,substra=feat/update-computeplan-status --tests=doc,camelyon,mnist,substrafl,sdk

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
/e2e --refs=orchestrator=feat/update-computeplan-status,substra-backend=feat/update-computeplan-status,substra=feat/update-computeplan-status --tests=doc,camelyon,mnist,substrafl,sdk

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
/e2e --refs=orchestrator=feat/update-computeplan-status,substra-backend=feat/update-computeplan-status,substra=feat/update-computeplan-status,substra-frontend=feat/update-computeplan-status --tests=doc,camelyon,mnist,substrafl,sdk

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
/e2e --refs=orchestrator=feat/update-computeplan-status,substra-backend=feat/update-computeplan-status,substra=feat/update-computeplan-status,substra-frontend=feat/update-computeplan-status --tests=doc,camelyon,mnist,substrafl,sdk

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
/e2e --refs=orchestrator=feat/update-computeplan-status,substra-backend=feat/update-computeplan-status,substra=feat/update-computeplan-status,substra-frontend=feat/update-computeplan-status --tests=doc,camelyon,mnist,substrafl,sdk

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
/e2e --refs=orchestrator=feat/update-computeplan-status,substra-backend=feat/update-computeplan-status,substra=feat/update-computeplan-status,substra-frontend=feat/update-computeplan-status --tests=doc,camelyon,mnist,substrafl,sdk

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Pull request merged**
