### PR TITLE
chore: restore parallelism

### PR DESCRIPTION
**Pull request by SdgJlbl**

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
There is a weird error, surely due to a merge conflict: `AssertionError: assert 'FUNCTION_STATUS_WAITING' == 'FUNCTION_STATUS_BUILDING'`

Also, just so you know, the syntax for choosing the test to run is `--tests sdk` :)

**Comment by SdgJlbl** [comment]
> There is a weird error, surely due to a merge conflict: `AssertionError: assert 'FUNCTION_STATUS_WAITING' == 'FUNCTION_STATUS_BUILDING'`
> 
> Also, just so you know, the syntax for choosing the test to run is `--tests sdk` :)

I think it's linked to the fact that we might need to wait a bit for the build to start, now that we are running tests in parallel again (and that the number of builders is smaller than the number of tests run in parallel). 
I'm looking into how best test the behaviour.

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by guilhem-barthes — APPROVED** [review]
LGTM !

**Pull request merged**
