### PR TITLE
feat: add tests to check cleaning of transient output assets

### PR DESCRIPTION
**Pull request by guilhem-barthes**
Fixes FL-1666

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
/e2e --refs orchestrator=fix/panic-when-disable-output-without-assets

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
/e2e --refs orchestrator=fix/panic-when-disable-output-without-assets --tests sdk,substrafl

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
/e2e --refs orchestrator=fix/panic-when-disable-output-without-assets --tests sdk,substrafl

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
/e2e --refs orchestrator=fix/panic-when-disable-output-without-assets --tests sdk,substrafl

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by thbcmlowk** [comment]
/e2e --refs orchestrator=fix/panic-when-disable-output-without-assets --tests sdk,substrafl

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by thbcmlowk — APPROVED** [review]
Thanks! 🩹

**Pull request merged**
