### PR TITLE
fix: flaky test_function_build_failure_different_backend

### PR DESCRIPTION
**Pull request by SdgJlbl**

### CODE REVIEW

**Review by thbcmlowk — APPROVED** [review]
LGTM, thanks! Should we merge it or wait for the release?

**Comment by SdgJlbl** [comment]
> LGTM, thanks! Should we merge it or wait for the release?

We are discussing with @guilhem-barthes for another fix that might fix both tests that have been flaky lately

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Pull request merged**
