### PR TITLE
feat: update tests to handle metadata

### PR DESCRIPTION
**Pull request by Kelvin-M**
Companion PRs : https://github.com/SubstraFoundation/substra-tools/pull/46, https://github.com/SubstraFoundation/substra-backend/pull/403

For this PR, we will need to do a release on substra-tools (0.8.0) to make it work properly.

### CODE REVIEW

**Comment by AurelienGasser** [comment]
Nice work? What do you think of adding a backwards compatibility test that would ensure that algos work even if they don't define a `metadata` parameter to the train function?

**Comment by Kelvin-M** [comment]
> Nice work! What do you think of adding a backwards compatibility test that would ensure that algos work even if they don't define a `metadata` parameter to the train function?

**Comment by Kelvin-M** [comment]
> Nice work! What do you think of adding a backwards compatibility test that would ensure that algos work even if they don't define a `metadata` parameter to the train function?

It won't be backward compatible because the substra-backend will put the `-- metadata XXX` argument if there are metadata in the tuple, so argparse will raise a `error: unrecognized arguments: --metadata XXX`

**Comment by AurelienGasser** [comment]
Here I'm talking about compatibility with existing algos, not between the backend and substra-tools

**Comment by AurelienGasser** [comment]
@Kelvin-M IMO this is problematic. Isn't there a way to add optional arguments with argparse? The altternative is that every user needs to rewrite their algo classes, which isn't great

**Comment by Kelvin-M** [comment]
There is a solution for that (see [here](https://stackoverflow.com/a/12818237)) for instance, but users will also need to rewrite their algo.
The issue does not come from the algo, but from substra-backend that cannot know if it should pass `--metadata` or not

**Pull request closed without merging**
