### PR TITLE
chore: rename tuple to task

### PR DESCRIPTION
**Pull request by ThibaultFy**
## Asana

https://app.asana.com/0/1203124674173179/1203842723899063/f

## Companion PRs

- https://github.com/Substra/substra-tests/pull/239
- https://github.com/Substra/substra/pull/337
- https://github.com/Substra/substrafl/pull/79

## E2E tests

- https://github.com/owkin/substra-ci/actions/runs/4044324704

### CODE REVIEW

**Comment by Owlfred** [comment]
```
Usage: /e2e [options] [help]

/e2e may appear anywhere as long as it is on its own line

Options:
  --refs <value>                                         Extra refs (branch or tag) with format REPO=GIT_REF,REPO=GIT_REF.
  Supported repositories: substra-hlf-k8s, orchestrator, substra-backend, substra-frontend, substra-tools, substrafl, substra, substra-tests, substra-ci.
  Example: /e2e --refs substra-backend=some_branch,orchestrator=some_tag (default: {})
  --tests-to-run, --tests <tests-to-run>                 Comma-separated list of tests to run. Valid options: sdk,substrafl,frontend or NONE. (default: "sdk")
  --benchmarks-to-run, --benchmarks <benchmarks-to-run>  Comma-separated list of workflows tests to run. Valid options: mnist, camelyon or NONE. (default: "NONE")
  --orchestrator-mode, --mode <orchestrator-mode>        Comma-separated list of orchestrator modes to run tests for. Valid options: standalone,distributed (default: "standalone,distributed")
  -h, --help                                             display help for command
```

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl --benchmarks mnist,camelyon --refs substra=rename-tuple-to-task,substrafl=rename-tuple-to-task

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by oleobal — APPROVED** [review]

**Pull request merged**
