### PR TITLE
chore: bump Pytorch version to 2.2.1 in tests

### PR DESCRIPTION
**Pull request by SdgJlbl**
Fixes CI following Python 3.12 support.

### CODE REVIEW

**Review by thbcmlowk — APPROVED** [review]
Thanks for fixing this! How can we make sure we spot this earlier next time?

**Comment by SdgJlbl** [comment]
> Thanks for fixing this! How can we make sure we spot this earlier next time?

I'm actually not sure 🤔 

The end-to-end tests were running fine, so I'm not sure... I guess that the matrices used are not exactly the same between the nightly and the manually triggered end-to-end tests, might be worth looking into it more deeply.

**Comment by thbcmlowk** [comment]
> > Thanks for fixing this! How can we make sure we spot this earlier next time?
> 
> I'm actually not sure 🤔
> 
> The end-to-end tests were running fine, so I'm not sure... I guess that the matrices used are not exactly the same between the nightly and the manually triggered end-to-end tests, might be worth looking into it more deeply.

Yes indeed, I think the local tests are actually never triggered except in the nightly. Can you create a follow-up task so we can look at it later? Thank you!

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Pull request merged**
