### PR TITLE
chore: unskip tests

### PR DESCRIPTION
**Pull request by SdgJlbl**
Still to unskip

- [ ] tests/test_execution.py::test_function_build_failure (waiting for fix in backend)
- [ ] tests/test_execution.py::test_aggregatetask (race condition)

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by SdgJlbl** [comment]
⬆️  only one unskipped test failed, to be fixed with [#807](https://github.com/Substra/substra-backend/pull/807)

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by thbcmlowk — APPROVED** [review]
💪

**Pull request merged**
