### PR TITLE
chore: update task profiling URL

### PR DESCRIPTION
**Pull request by guilhem-barthes**
Fixes FL-1649

### CODE REVIEW

**Comment by guilhem-barthes** [comment]
/e2e --tests sdk,substrafl,doc,mnist,camelyon,frontend --refs substra-backend=feat/align-task-profiling-function-profiling,substra-frontend=feat/align-task-profiling-function-profiling

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
/e2e --tests sdk --refs substra-backend=feat/align-task-profiling-function-profiling,substra-frontend=feat/align-task-profiling-function-profiling

**Comment by guilhem-barthes** [comment]
/e2e --tests sdk --refs substra-backend=feat/align-task-profiling-function-profiling,substra-frontend=feat/align-task-profiling-function-profiling

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
/e2e --tests sdk --refs substra-backend=feat/align-task-profiling-function-profiling,substra-frontend=feat/align-task-profiling-function-profiling

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
/e2e --tests sdk --refs substra-backend=feat/align-task-profiling-function-profiling,substra-frontend=feat/align-task-profiling-function-profiling

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Pull request closed without merging**
