### PR TITLE
feat: add first tests on builder

### PR DESCRIPTION
**Pull request by guilhem-barthes**
# Description

Check that build is launched when function is created, and that they are build in the right order. Part of FL-1147

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
Might need a rebase to relaunch the e2e tests on it

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by SdgJlbl — APPROVED** [review]
🙏

**Pull request merged**
