### PR TITLE
refactor: algo category from AlgoSpec

### PR DESCRIPTION
**Pull request by louishulot**
Companion PRs:
substra-tests: https://github.com/Substra/substra-tests/pull/219 (here)
substrafl: https://github.com/Substra/substrafl/pull/29
substra: https://github.com/Substra/substra/pull/294 (main)
documentation: https://github.com/Substra/substra-documentation/pull/186
orchestrator: https://github.com/Substra/orchestrator/pull/42
backend: https://github.com/Substra/substra-backend/pull/487

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by louishulot** [comment]
/e2e --refs substra=gt/remove_algo_category,substra-tests=gt/remove_algo_category,substrafl=gt/remove_algo_category --tests sdk,substrafl --benchmarks mnist,camelyon

**Comment by louishulot** [comment]
/e2e --refs substra=gt/remove_algo_category,substra-tests=gt/remove_algo_category,substrafl=gt/remove_algo_category,substra-backend=gt/remove_algo_category --tests sdk,substrafl

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by louishulot** [comment]
/e2e --refs substra=gt/remove_algo_category,substra-tests=gt/remove_algo_category,substrafl=gt/remove_algo_category,substra-backend=gt/remove_algo_category,orchestrator=gt/remove_algo_category --tests sdk,substrafl,frontend

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
```
Usage: /e2e [options] [help]

/e2e may appear anywhere as long as it is on its own line

Options:
  --refs <value>                                         Extra refs (branch or tag) with format REPO=GIT_REF,REPO=GIT_REF.
  Supported repositories: substra-hlf-k8s, orchestrator, substra-backend, substra-frontend, substra-tools, substrafl, substra, substra-tests, connect-ci.
  Example: /e2e --refs substra-backend=some_branch,orchestrator=some_tag (default: {})
  --tests-to-run, --tests <tests-to-run>                 Comma-separated list of tests to run. Valid options: sdk,substrafl,frontend or NONE. (default: "sdk")
  --benchmarks-to-run, --benchmarks <benchmarks-to-run>  Comma-separated list of workflows tests to run. Valid options: mnist, camelyon or NONE. (default: "NONE")
  --orchestrator-mode, --mode <orchestrator-mode>        Comma-separated list of orchestrator modes to run tests for. Valid options: standalone,distributed (default: "standalone,distributed")
  -h, --help                                             display help for command
```

**Comment by louishulot** [comment]
/e2e --refs substra=gt/remove_algo_category,substra-tests=gt/remove_algo_category,substrafl=gt/remove_algo_category,substra-backend=gt/remove_algo_category,orchestrator=gt/remove_algo_category --tests sdk,substrafl,frontend  --benchmarks mnist,camelyon

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Pull request merged**
