### PR TITLE
fix: download build failure logs

### PR DESCRIPTION
**Pull request by SdgJlbl**

### CODE REVIEW

**Comment by ThibaultFy** [comment]
Could you add the companion PRs or linear card, and launch the e2e tests on it please ? It's hard to get the whole context without the different interaction this PR could have :/

**Comment by SdgJlbl** [comment]
Sorry I pushed it in a rush yesterday evening so that everyone could access the failing test, I'll revert it to draft for now.

**Comment by Owlfred** [comment]
```
Usage: /e2e [options] [help]

/e2e may appear anywhere as long as it is on its own line

Options:
  --refs <value>                          Extra refs (branch or tag) with format REPO=GIT_REF,REPO=GIT_REF.
  Supported repositories: orchestrator, substra-backend, substra-frontend, substra-tools, substrafl, substra, substra-tests, substra-documentation, substra-ci.
  Example: /e2e --refs substra-backend=some_branch,orchestrator=some_tag (default: {})
  --tests-to-run, --tests <tests-to-run>  Comma-separated list of tests to run. Valid options: sdk, substrafl, doc, frontend, mnist, camelyon or NONE. (default: "sdk")
  -h, --help                              display help for command
```

**Comment by SdgJlbl** [comment]
/e2e --tests sdk,mnist,camelyon --refs substra_backend=feat/logs-from-task,substra=feat/download-task-logs

**Comment by Owlfred** [comment]
Invalid repository in --refs: "substra_backend". Supported repositories: orchestrator, substra-backend, substra-frontend, substra-tools, substrafl, substra, substra-tests, substra-documentation, substra-ci

**Comment by SdgJlbl** [comment]
/e2e --tests sdk,mnist,camelyon --refs substra-backend=feat/logs-from-task,substra=feat/download-task-logs

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
/e2e --tests sdk,mnist,camelyon --refs substra-backend=feat/logs-from-task,substra=feat/download-task-logs,orchestrator=fix/function-action-propagation

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by ThibaultFy — APPROVED** [review]
LGTM, maybe a word of this new test in the changelog ?

**Pull request merged**
