### PR TITLE
chore: rename algo to function

### PR DESCRIPTION
**Pull request by ThibaultFy**
## Description

Rename Algo concept to Function on all the stack.

## Companion PRs

- https://github.com/Substra/orchestrator/pull/139
- https://github.com/Substra/substra-backend/pull/573
- https://github.com/Substra/substra-tests/pull/243
- https://github.com/Substra/substra/pull/341
- https://github.com/Substra/substrafl/pull/82
- https://github.com/Substra/substra-documentation/pull/264
- https://github.com/Substra/substra-frontend/pull/170

### CODE REVIEW

**Comment by ThibaultFy** [comment]
/e2e --test sdk,substrafl --benchmarks mnist,camelyon --refs substra=rename-algo-to-function,substrafl=rename-algo-to-function,orchestrator=rename-algo-to-function,substra-backend=rename-algo-to-function,substra-tests=rename-algo-to-function

**Comment by Owlfred** [comment]
Something happened while processing your message: error: unknown option '--test'
(Did you mean --tests?)

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl --benchmarks mnist,camelyon --refs substra=rename-algo-to-function,substrafl=rename-algo-to-function,orchestrator=rename-algo-to-function,substra-backend=rename-algo-to-function,substra-tests=rename-algo-to-function

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,frontend --benchmarks mnist,camelyon --refs substra=rename-algo-to-function,substrafl=rename-algo-to-function,orchestrator=rename-algo-to-function,substra-backend=rename-algo-to-function,substra-tests=rename-algo-to-function,substra-frontend=rename-algo-to-function

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,frontend --benchmarks mnist,camelyon --refs substra=rename-algo-to-function,substrafl=rename-algo-to-function,orchestrator=rename-algo-to-function,substra-backend=rename-algo-to-function,substra-tests=rename-algo-to-function,substra-frontend=rename-algo-to-function

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,frontend --benchmarks mnist,camelyon --refs substra=rename-algo-to-function,substrafl=rename-algo-to-function,orchestrator=rename-algo-to-function,substra-backend=rename-algo-to-function,substra-tests=rename-algo-to-function,substra-frontend=rename-algo-to-function

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,frontend --benchmarks mnist,camelyon --refs substra=rename-algo-to-function,substrafl=rename-algo-to-function,orchestrator=rename-algo-to-function,substra-backend=rename-algo-to-function,substra-tests=rename-algo-to-function,substra-frontend=rename-algo-to-function

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,frontend --benchmarks mnist,camelyon --refs substra=rename-algo-to-function,substrafl=rename-algo-to-function,orchestrator=rename-algo-to-function,substra-backend=rename-algo-to-function,substra-tests=rename-algo-to-function,substra-frontend=rename-algo-to-function

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,frontend --benchmarks mnist,camelyon --refs substra=rename-algo-to-function,substrafl=rename-algo-to-function,orchestrator=rename-algo-to-function,substra-backend=rename-algo-to-function,substra-tests=rename-algo-to-function,substra-frontend=rename-algo-to-function

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,frontend --benchmarks mnist,camelyon --refs substra=rename-algo-to-function,substrafl=rename-algo-to-function,orchestrator=rename-algo-to-function,substra-backend=rename-algo-to-function,substra-tests=rename-algo-to-function,substra-frontend=rename-algo-to-function

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,frontend --benchmarks mnist,camelyon --refs substra=rename-algo-to-function,substrafl=rename-algo-to-function,orchestrator=rename-algo-to-function,substra-backend=rename-algo-to-function,substra-tests=rename-algo-to-function,substra-frontend=rename-algo-to-function

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,frontend --benchmarks mnist,camelyon --refs substra=rename-algo-to-function,substrafl=rename-algo-to-function,orchestrator=rename-algo-to-function,substra-backend=rename-algo-to-function,substra-tests=rename-algo-to-function,substra-frontend=rename-algo-to-function

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,frontend --benchmarks mnist,camelyon --refs substra=rename-algo-to-function,substrafl=rename-algo-to-function,orchestrator=rename-algo-to-function,substra-backend=rename-algo-to-function,substra-tests=rename-algo-to-function,substra-frontend=rename-algo-to-function

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,frontend --benchmarks mnist,camelyon --refs substra=rename-algo-to-function,substrafl=rename-algo-to-function,orchestrator=rename-algo-to-function,substra-backend=rename-algo-to-function,substra-tests=rename-algo-to-function,substra-frontend=rename-algo-to-function

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,frontend --benchmarks mnist,camelyon --refs substra=rename-algo-to-function,substrafl=rename-algo-to-function,orchestrator=rename-algo-to-function,substra-backend=rename-algo-to-function,substra-tests=rename-algo-to-function,substra-frontend=rename-algo-to-function

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,frontend --benchmarks mnist,camelyon --refs substra=rename-algo-to-function,substrafl=rename-algo-to-function,orchestrator=rename-algo-to-function,substra-backend=rename-algo-to-function,substra-tests=rename-algo-to-function,substra-frontend=rename-algo-to-function

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests substrafl--benchmarks NONE --refs substra=rename-algo-to-function,substrafl=rename-algo-to-function,orchestrator=rename-algo-to-function,substra-backend=rename-algo-to-function,substra-tests=rename-algo-to-function,substra-frontend=rename-algo-to-function

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests substrafl--benchmarks NONE --refs substra=rename-algo-to-function,substrafl=rename-algo-to-function,orchestrator=rename-algo-to-function,substra-backend=rename-algo-to-function,substra-tests=rename-algo-to-function,substra-frontend=rename-algo-to-function

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,frontend --benchmarks mnist,camelyon --refs substra=rename-algo-to-function,substrafl=rename-algo-to-function,orchestrator=rename-algo-to-function,substra-backend=rename-algo-to-function,substra-tests=rename-algo-to-function,substra-frontend=rename-algo-to-function

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by oleobal — APPROVED** [review]

**Pull request merged**
