### PR TITLE
fix: new substra client configuration

### PR DESCRIPTION
**Pull request by SdgJlbl**

### CODE REVIEW

**Comment by Owlfred** [comment]
```
Usage: /e2e [options] [help]

/e2e may appear anywhere as long as it is on its own line

Options:
  --refs <value>                                         Extra refs (branch or tag) with format REPO=GIT_REF,REPO=GIT_REF.
  Supported repositories: hlf-k8s, orchestrator, substra-backend, substra-frontend, substra-tools, substrafl, substra, substra-tests, substra-ci.
  Example: /e2e --refs substra-backend=some_branch,orchestrator=some_tag (default: {})
  --tests-to-run, --tests <tests-to-run>                 Comma-separated list of tests to run. Valid options: sdk,substrafl,frontend or NONE. (default: "sdk")
  --benchmarks-to-run, --benchmarks <benchmarks-to-run>  Comma-separated list of workflows tests to run. Valid options: mnist, camelyon or NONE. (default: "NONE")
  --orchestrator-mode, --mode <orchestrator-mode>        Comma-separated list of orchestrator modes to run tests for. Valid options: standalone,distributed (default: "standalone,distributed")
  -h, --help                                             display help for command
```

**Comment by SdgJlbl** [comment]
/e2e --mode standalone --benchmarks camelyon,mnist --refs substra=feat/client-configuration-with-env-var

**Comment by SdgJlbl** [comment]
/e2e --mode standalone --benchmarks camelyon,mnist --refs substra=feat/client-configuration-with-env-var

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by SdgJlbl** [comment]
/e2e --mode standalone --benchmarks camelyon,mnist --refs substra=feat/client-configuration-with-env-var

**Comment by SdgJlbl** [comment]
/e2e --mode standalone --benchmarks camelyon,mnist --refs substra=feat/client-configuration-with-env-var

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
```
Usage: /e2e [options] [help]

/e2e may appear anywhere as long as it is on its own line

Options:
  --refs <value>                                         Extra refs (branch or tag) with format REPO=GIT_REF,REPO=GIT_REF.
  Supported repositories: hlf-k8s, orchestrator, substra-backend, substra-frontend, substra-tools, substrafl, substra, substra-tests, substra-ci.
  Example: /e2e --refs substra-backend=some_branch,orchestrator=some_tag (default: {})
  --tests-to-run, --tests <tests-to-run>                 Comma-separated list of tests to run. Valid options: sdk,substrafl,frontend or NONE. (default: "sdk")
  --benchmarks-to-run, --benchmarks <benchmarks-to-run>  Comma-separated list of workflows tests to run. Valid options: mnist, camelyon or NONE. (default: "NONE")
  --orchestrator-mode, --mode <orchestrator-mode>        Comma-separated list of orchestrator modes to run tests for. Valid options: standalone,distributed (default: "standalone,distributed")
  -h, --help                                             display help for command
```

**Comment by SdgJlbl** [comment]
/e2e --mode standalone --benchmarks camelyon,mnist --refs substra=feat/client-configuration-with-env-var substrafl=fix/fix-benchmarks

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by SdgJlbl** [comment]
/e2e --mode standalone --benchmarks camelyon,mnist --refs substra=feat/client-configuration-with-env-var,substrafl=fix/fix-benchmarks

**Review by ThibaultFy — APPROVED** [review]
Comment on log level info, but not blocking for the merge IMO

**Pull request merged**
